# Generated by Django 5.1.6 on 2025-03-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionentry',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
