# Generated by Django 5.1.6 on 2025-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.CharField(help_text='The bullet point', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='The name of the institution', max_length=100)),
                ('area', models.CharField(help_text='The area of study', max_length=100)),
                ('degree', models.CharField(blank=True, help_text='The type of degree (e.g., BS, MS, PhD)', max_length=100)),
                ('location', models.CharField(blank=True, help_text='The location', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='The start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The end date', null=True)),
                ('date', models.DateField(blank=True, help_text='Custom date (overrides start_date and end_date)', null=True)),
                ('summary', models.CharField(blank=True, help_text='Summary of the entry', max_length=500)),
                ('highlights', models.CharField(blank=True, help_text='List of highlights separated by <;>', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='The name of the company', max_length=100)),
                ('position', models.CharField(help_text='The position', max_length=100)),
                ('location', models.CharField(blank=True, help_text='The location', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='The start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The end date', null=True)),
                ('date', models.DateField(blank=True, help_text='Custom date (overrides start_date and end_date)', null=True)),
                ('summary', models.CharField(blank=True, help_text='Summary of the entry', max_length=500)),
                ('highlights', models.CharField(blank=True, help_text='List of highlights separated by <;>', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NormalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the entry', max_length=100)),
                ('location', models.CharField(blank=True, help_text='The location', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='The start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The end date', null=True)),
                ('date', models.DateField(blank=True, help_text='Custom date (overrides start_date and end_date)', null=True)),
                ('summary', models.CharField(blank=True, help_text='Summary of the entry', max_length=500)),
                ('highlights', models.CharField(blank=True, help_text='List of highlights separated by <;>', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NumberedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='The numbered entry content', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OneLineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The label of the entry', max_length=100)),
                ('details', models.CharField(help_text='The details of the entry', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the publication', max_length=200)),
                ('authors', models.CharField(help_text='The authors (separated by commas)', max_length=300)),
                ('doi', models.CharField(blank=True, help_text='The DOI of the publication', max_length=100)),
                ('url', models.URLField(blank=True, help_text='The URL of the publication')),
                ('journal', models.CharField(blank=True, help_text='The journal of the publication', max_length=200)),
                ('date', models.DateField(blank=True, help_text='The publication date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReversedNumberedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversed_number', models.CharField(help_text='The reversed numbered entry content', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text content for the entry')),
            ],
        ),
    ]
