# Generated by Django 5.1.6 on 2025-03-06 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('bullet', models.CharField(help_text='The bullet point', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('institution', models.CharField(help_text='The name of the institution', max_length=100)),
                ('area', models.CharField(help_text='The area of study', max_length=100)),
                ('degree', models.CharField(blank=True, help_text='The type of degree (e.g., BS, MS, PhD)', max_length=100)),
                ('location', models.CharField(blank=True, help_text='The location', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='The start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The end date', null=True)),
                ('date', models.DateField(blank=True, help_text='Custom date (overrides start_date and end_date)', null=True)),
                ('summary', models.CharField(blank=True, help_text='Summary of the entry', max_length=500)),
                ('highlights', models.CharField(blank=True, help_text='List of highlights separated by ;', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('company', models.CharField(help_text='The name of the company', max_length=100)),
                ('position', models.CharField(help_text='The position', max_length=100)),
                ('location', models.CharField(blank=True, help_text='The location', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='The start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The end date', null=True)),
                ('date', models.DateField(blank=True, help_text='Custom date (overrides start_date and end_date)', null=True)),
                ('summary', models.CharField(blank=True, help_text='Summary of the entry', max_length=500)),
                ('highlights', models.CharField(blank=True, help_text='List of highlights separated by ;', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NormalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('name', models.CharField(help_text='The name of the entry', max_length=100)),
                ('location', models.CharField(blank=True, help_text='The location', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='The start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The end date', null=True)),
                ('date', models.DateField(blank=True, help_text='Custom date (overrides start_date and end_date)', null=True)),
                ('summary', models.CharField(blank=True, help_text='Summary of the entry', max_length=500)),
                ('highlights', models.CharField(blank=True, help_text='List of highlights separated by ;', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('number', models.CharField(help_text='The numbered entry content', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneLineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('label', models.CharField(help_text='The label of the entry', max_length=100)),
                ('details', models.CharField(help_text='The details of the entry', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('title', models.CharField(help_text='The title of the publication', max_length=200)),
                ('authors', models.CharField(help_text='The authors (separated by commas)', max_length=300)),
                ('doi', models.CharField(blank=True, help_text='The DOI of the publication', max_length=100)),
                ('url', models.URLField(blank=True, help_text='The URL of the publication')),
                ('journal', models.CharField(blank=True, help_text='The journal of the publication', max_length=200)),
                ('date', models.DateField(blank=True, help_text='Custom date (overrides start_date and end_date)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReversedNumberedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('reversed_number', models.CharField(help_text='The reversed numbered entry content', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('text', models.TextField(help_text='The text content for the entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
