# Generated by Django 5.1.6 on 2025-03-13 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='bulletentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bulletentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='educationentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='educationentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='educationentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experienceentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='experienceentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experienceentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='normalentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='normalentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='normalentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='numberedentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='numberedentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='numberedentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='onelineentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='onelineentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='onelineentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publicationentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='publicationentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publicationentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reversednumberedentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='reversednumberedentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reversednumberedentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textentry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='textentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textentry',
            name='user',
        ),
        migrations.CreateModel(
            name='BaseEntry',
            fields=[
                ('alias', models.CharField(help_text='Alias for the CV entry', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bulletentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normalentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberedentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onelineentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reversednumberedentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textentry',
            name='baseentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.baseentry'),
            preserve_default=False,
        ),
    ]
