# Generated by Django 5.1.6 on 2025-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cventry',
            name='alias',
            field=models.CharField(default='null', help_text='Alias for the CV entry', max_length=20),
            preserve_default=False,
        ),
    ]
