# Generated by Django 5.1.6 on 2025-02-15 21:11

import cv.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('professional', 'Professional'), ('minimalist', 'Minimalist'), ('custom', 'Custom')], help_text='The theme name', max_length=100)),
                ('custom_design', models.FileField(blank=True, help_text='Upload a custom design file', null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_designs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the individual', max_length=255)),
                ('location', models.CharField(blank=True, help_text='The location of the individual', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='The email address of the individual', max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, help_text="Path to the individual's photo", null=True, upload_to='photos/')),
                ('phone', models.CharField(blank=True, help_text='The phone number, including country code', max_length=20, null=True)),
                ('website', models.URLField(blank=True, help_text="A URL to the individual's personal or professional website", null=True)),
                ('social_networks', models.JSONField(blank=True, help_text='A list of social media profiles in JSON format', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The date that will be used for various computations (default: today)')),
                ('bold_keywords', models.JSONField(blank=True, default=list, help_text='A list of keywords that will be bolded in the output')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.cvdesign')),
            ],
        ),
        migrations.CreateModel(
            name='CVEntryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.cventry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='entries',
            field=models.ManyToManyField(through='cv.CVEntryOrder', to='entries.cventry'),
        ),
        migrations.CreateModel(
            name='CVLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', help_text='The language as an ISO 639 alpha-2 code', max_length=2)),
                ('phone_number_format', models.CharField(blank=True, choices=[('national', 'National'), ('international', 'International'), ('E164', 'E164')], default='national', help_text='The format of phone numbers (national, international, or E164)', max_length=20)),
                ('page_numbering_template', models.CharField(default='NAME - Page PAGE_NUMBER of TOTAL_PAGES', help_text='The template for page numbering in the CV.', max_length=255)),
                ('last_updated_date_template', models.CharField(default='Last updated in TODAY', help_text='The template for the last updated date.', max_length=255)),
                ('date_template', models.CharField(blank=True, default='MONTH_ABBREVIATION YEAR', help_text='The template for dates.', max_length=255)),
                ('month', models.CharField(blank=True, default='month', help_text="Translation of the word 'month' in the locale.", max_length=100)),
                ('months', models.CharField(blank=True, default='months', help_text="Translation of the word 'months' in the locale.", max_length=100)),
                ('year', models.CharField(blank=True, default='year', help_text="Translation of the word 'year' in the locale.", max_length=100)),
                ('years', models.CharField(blank=True, default='years', help_text="Translation of the word 'years' in the locale.", max_length=100)),
                ('present', models.CharField(blank=True, default='present', help_text="Translation of the word 'present' in the locale.", max_length=100)),
                ('to', models.CharField(blank=True, default='–', help_text="The word or character used to indicate a range (e.g., '2020 - 2021').", max_length=10)),
                ('abbreviations_for_months', models.JSONField(blank=True, default=cv.models.ABBREVIATIONSSFORMONTHS_DEFAULT, help_text='Abbreviations of the months in the locale.')),
                ('full_names_of_months', models.JSONField(blank=True, default=cv.models.FULLNAMESOFMONTHS_DEFAULT, help_text='Full names of the months in the locale.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_locales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.cvlocale'),
        ),
        migrations.AddConstraint(
            model_name='cventryorder',
            constraint=models.UniqueConstraint(fields=('cv', 'order'), name='unique_cv_order'),
        ),
    ]
