# Generated by Django 5.1.6 on 2025-03-14 11:16

import cv.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('alias', models.CharField(default='CV', help_text='Alias for the curriculum vitae', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVDesign',
            fields=[
                ('alias', models.CharField(default='default', help_text='Alias for the design', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('theme', models.CharField(choices=[('classic', 'Classic'), ('sb2nov', 'Sb2Nov'), ('engineeringresumes', 'EngineeringResumes'), ('engineeringclassic', 'EngineeringClassic'), ('moderncv', 'ModernCV')], help_text='The theme name', max_length=100)),
                ('design_file', models.FileField(blank=True, help_text='Upload YAML file with complete design specs', null=True, upload_to='media/cvs/src')),
            ],
        ),
        migrations.CreateModel(
            name='CVInfo',
            fields=[
                ('alias', models.CharField(default='default', help_text='Alias for the information', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Your name', max_length=20, null=True)),
                ('location', models.CharField(blank=True, help_text='The location of the individual', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='The email address of the individual', max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, help_text="Path to the individual's photo", null=True, upload_to='photos/')),
                ('phone', models.CharField(blank=True, help_text='The phone number, including country code', max_length=20, null=True)),
                ('website', models.URLField(blank=True, help_text="A URL to the individual's personal or professional website", null=True)),
                ('social_networks', models.JSONField(blank=True, help_text='A list of social media profiles in JSON format', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVLocale',
            fields=[
                ('alias', models.CharField(default='default', help_text='Alias for the locale', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(default='en', help_text='The language as an ISO 639 alpha-2 code', max_length=2)),
                ('phone_number_format', models.CharField(blank=True, choices=[('national', 'National'), ('international', 'International'), ('E164', 'E164')], default='national', help_text='The format of phone numbers (national, international, or E164)', max_length=20)),
                ('page_numbering_template', models.CharField(default='NAME - Page PAGE_NUMBER of TOTAL_PAGES', help_text='The template for page numbering in the CV.', max_length=255)),
                ('last_updated_date_template', models.CharField(default='Last updated in TODAY', help_text='The template for the last updated date.', max_length=255)),
                ('date_template', models.CharField(blank=True, default='MONTH_ABBREVIATION YEAR', help_text='The template for dates.', max_length=255)),
                ('month', models.CharField(blank=True, default='month', help_text="Translation of the word 'month' in the locale.", max_length=100)),
                ('months', models.CharField(blank=True, default='months', help_text="Translation of the word 'months' in the locale.", max_length=100)),
                ('year', models.CharField(blank=True, default='year', help_text="Translation of the word 'year' in the locale.", max_length=100)),
                ('years', models.CharField(blank=True, default='years', help_text="Translation of the word 'years' in the locale.", max_length=100)),
                ('present', models.CharField(blank=True, default='present', help_text="Translation of the word 'present' in the locale.", max_length=100)),
                ('to', models.CharField(blank=True, default='–', help_text="The word or character used to indicate a range (e.g., '2020 - 2021').", max_length=10)),
                ('abbreviations_for_months', models.JSONField(blank=True, default=cv.models.months_abbreviations_defaults, help_text='Abbreviations of the months in the locale.')),
                ('full_names_of_months', models.JSONField(blank=True, default=cv.models.months_full_names_defaults, help_text='Full names of the months in the locale.')),
                ('locale_file', models.FileField(blank=True, help_text='Upload YAML file with complete locale settings', null=True, upload_to='media/cvs/src')),
            ],
        ),
        migrations.CreateModel(
            name='CVSettings',
            fields=[
                ('alias', models.CharField(default='default', help_text='Alias for the settings', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The date that will be used for various computations (default: today)')),
                ('bold_keywords', models.JSONField(blank=True, default=list, help_text='A list of keywords that will be bolded in the output')),
                ('settings_file', models.FileField(blank=True, help_text='Upload YAML file with complete settings', null=True, upload_to='media/cvs/src')),
            ],
        ),
    ]
