# Generated by Django 5.1.6 on 5-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default="2025-02-18"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='alias',
            field=models.CharField(default='CV', help_text='Alias for the curriculum vitae', max_length=20),
        ),
        migrations.AlterField(
            model_name='cvdesign',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('sb2nov', 'Sb2Nov'), ('engineeringresumes', 'EngineeringResumes'), ('engineeringclassic', 'EngineeringClassic'), ('moderncv', 'ModernCV')], help_text='The theme name', max_length=100),
        ),
    ]
