# Generated by Django 5.1.6 on 2025-07-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdesign',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('sb2nov', 'Sb2Nov'), ('engineeringresumes', 'EngineeringResumes'), ('engineeringclassic', 'EngineeringClassic'), ('moderncv', 'ModernCV'), ('custom', 'Custom')], help_text='The theme name', max_length=100),
        ),
    ]
