# Generated by Django 5.1.6 on 2025-03-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_created_date_cv_modified_date_alter_cv_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
    ]
