# Generated by Django 5.1.6 on 2025-03-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv', to='cv.cvdesign'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv', to='cv.cvinfo'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv', to='cv.cvlocale'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv', to='cv.cvsettings'),
        ),
    ]
