# Generated by Django 5.1.6 on 2025-03-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_design_alter_cv_info_alter_cv_locale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvinfo',
            name='data_file',
        ),
    ]
