# Generated by Django 5.1.6 on 2025-03-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_section_user'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfosection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
        migrations.AlterField(
            model_name='sectionentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_entries', to='sections.section'),
        ),
        migrations.AlterField(
            model_name='cvinfo',
            name='sections',
            field=models.ManyToManyField(related_name='cv_infos', through='cv.CVInfoSection', to='sections.section'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
