# Generated by Django 5.1.6 on 2025-03-13 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_cvinfo_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
